apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    name: myapp-deployment
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-deployment
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp-deployment
    spec:
      containers:
        - name: myapp-cont
          image: ngnix
