apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: first-replicaset
  labels:
    name: myrep
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: mypod
      labels:
        app: myapp
    spec:
      containers:
        - name: mycont
          image: ngnix
